spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**, /api/profile/**

        - id: startup-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/startups/**, /api/documents/**

        - id: investor-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/investor/** , /api/investment , /api/investors/preferences
server:
  port: 8080