INSERT INTO industry (name, active) VALUES
('FinTech', true),
('HealthTech', true),
('EdTech', true),
('E-commerce', true),
('SaaS', true),
('Artificial Intelligence', true),
('Machine Learning', true),
('Blockchain', true),
('Cybersecurity', true),
('AgriTech', true),
('FoodTech', true),
('TravelTech', true),
('Real Estate', true),
('Logistics', true),
('Gaming', true),
('Social Media', true),
('Clean Energy', true),
('Climate Tech', true),
('Biotechnology', true),
('Automotive', true),
('Manufacturing', true),
('Retail', true),
('Telecommunications', true),
('Media & Entertainment', true),
('Fitness & Wellness', true);